### ISSUE TITLE
who is going to use this chit chat

### ISSUE THREAD

**Issue by vaibhav2ghadge** [ryanpback/chit_chat_backend#1]
- Can you more elaborate the user of this project

**Comment by ryanpback** [comment]
The ultimate goal would be that anybody could subscribe, add users under their account, throw a script on their website (or go to the website/maybe future app), and start chatting to the other users.

In the case of adding a script to their website, the message app would sit in the corner ready to be used - think LinkedIn.

Again, this is mostly a side project that is for fun and a chance to learn. I know when I started out developing, coming up with real world projects was always the most difficult thing.

**Comment by danrleypereira** [comment]
I just started to do things using golang, mostly newbies logical problems. 
I can't figure out where is the dist folder referenced at build.sh;
If is it to learning purpose, the first thing we can do is write a README.md with more information about how to run correctly. Maybe improve the build.sh to more than one use case? 

I already done some stuff using angular, vue, java, c. Now I am learning more about React and just started to figure out how Golang works, I want to learn a new programming paradigm.
Thank you to the opportunity!

My OS is debian 9

**Comment by ryanpback** [comment]
Hey @danrleywillyan! Thanks for touching base.

So, the dust folder is created when you build the binary. In the case of your Debian machine, we’ll need to add another build step so that a Linux binary is created. I deforest agree that the README needs a lot of work and the build script should be able to account for anybody’s credentials for their local machine.

That’s awesome you’ve worked with so many languages. I love Vue, but thought it would be good to do a full build with React. My background is Ruby, PHP, Vue, React, Go, and some C++.

The opportunity is most welcome! 🙂
